server:
  port: 8085
  servlet:
    context-path: /ctp-paas-monitor
spring:
  application:
    name: ctp-paas-monitor
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 将gateway注册到nacos
feign:
  client:
    config:
      default:
        connectTimeout: 120000
        readTimeout: 120000
  httpclient:
    enabled: false
  okhttp:
    enabled: true

#配置业务线程池
threadpool:
  coreNum: 8
  maxNum: 16

#netty配置
netty:
  #启动端口
  port: 8899
  #客户端读超时秒数
  readTimeoutSeconds: 60