server:
  port: 8085
  servlet:
    context-path: /cgp-paas-resource
spring:
  application:
    name: cgp-paas-resource
  cloud:
    nacos:
      discovery:
        server-addr: 121.36.87.91:8848 # 将gateway注册到nacos
feign:
  client:
    config:
      default:
        connectTimeout: 120000
        readTimeout: 120000
  okhttp:
    enabled: true
  hystrix:
    enabled: false
  httpclient:
    max-connections: 500
    enabled: false

#配置业务线程池
threadpool:
  coreNum: 8
  maxNum: 16

#netty配置
netty:
  #启动端口
  port: 8899
  #客户端读超时秒数
  readTimeoutSeconds: 300